### ISSUE TITLE
Automate Volunteer Signup

### ISSUE THREAD

**Issue by khandelwalrinki** [womenhackfornonprofits/whfnp-wiki#12]
# What

Currently, onboarding of new members requires a lot of manual actions, and is not self-processing. We gain a lot of our new members on Meetup, but there is too much process between this and being onboarded into the Slack community + being added to the newsletter and sending an onboarding email. 

We need to enable Slack self-signup and automate the onboarding process so board member availability doesn't become a bottleneck, and we have a much more streamlined process between our Meetup and Slack communities and physical events.

# Tasks

_Whoever picks this up, feel free to create separate tickets and reference this one for each of below if needed_

- [ ] Open slack signup to public, this requires building a slack self signup page using Slack API
- [ ] Rewrite onboarding email, point them to essential channels/resources and Slack self-signup link amend the onboaridng template email linked in onboarding channel and also amend the Meetup group with the new email in the group settings when new users signup and email is displayed to them.
- [ ] Automate this with our website volunteer signup form: When volunteer signs up at http://www.womenhackfornonprofits.com/volunteer-contact.html, automatically send the onboarding email and add to our mailing list.
