### ISSUE TITLE
Regular Call For Volunteers

### ISSUE THREAD

**Issue by khandelwalrinki** [womenhackfornonprofits/whfnp-wiki#13]
# What

Create a central slide-deck for project status updates; this will be shown in presentations and be a visual screenshot we share in Slack channel #nonprofits-needshelp whenever a project needs a fresh call for volunteers. We can share these screenshots on twitter and external sources too.

This is to post regular updates in an engaging, visual way, rather than just text.

We will continue to use our [Current Projects Wiki page](https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Current-Projects) as our central source of summary information about projects and their links. This slide deck will be linked on top of it. Its purpose is to be kept up-to-date about the _current status_ of projects. We will communicate this and open access to all project leads, who'll have the responsibility of keeping their slide and project wiki info up-to-date.

[Example of current slide deck to base this off](http://slides.com/krissygoround/whfnp-hack-eve-20161116#/) (feel free to tweak template, e.g. probably best to add logo on all slides so always present in screenshots)

# Tasks

_Whoever picks this up, feel free to create separate tickets and reference this one for each of below if needed_

- [ ] Create a slides.com WHFNP account and add login details to our master doc
- [ ] Add a rolling WHFNP Project Status slide deck (copy over from Krissy's or Lili's account)
- [ ] Add link to slide deck to https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Current-Projects
- [ ] Give all board members and project leads in Slack #whfnp-project-leads room edit access to slide deck and communicate to keep this up to date
