### ISSUE TITLE
Review and update WHFNP resources + tech-specific Slack channels

### ISSUE THREAD

**Issue by khandelwalrinki** [womenhackfornonprofits/whfnp-wiki#15]
# What

A growing member of our community are those new to code or learning new technology skills. We want to engage them better and activate them.

We need to review our use of Slack channels and [our code practice resources wiki page](https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Online-Resources-to-Learn-and-Practice-Your-Coding-Skills) to make it clear, simple and less confusing for our members who want to activate and engage.

# Tasks

- [ ] List our existing slack channels that provide support / dedicate conversation to learning tech. E.g. #stack-overflow, #frontend, #javascript, #django etc. Add these to the top of the tech resources page, so members know they have a community of members to collaborate with about specific tech stacks. Create new channels if necessary and add to the list.
- [ ] Review/update the wiki page, removing any stale links and ensuring it's easily navigable by tech stack / topic.
- [ ] Once done, broadcast in Slack and Twitter to point people to the resources page and helpful slack channels.
