### ISSUE TITLE
Django/Python Focused Hack Evening/Hack Day 

### ISSUE THREAD

**Issue by khandelwalrinki** [womenhackfornonprofits/whfnp-wiki#18]
# What

We want to trial our first tech-stack focussed Hack day, in order to engage our volunteers (beginners, experienced, mentors) better and start collaborating with other orgs/companies/sponsors by targeting specific technology groups.

This day will be a parallel mix of existing project hacking, project planning for new projects with Django as their intended stack and beginner Django workshop given by willing volunteers or host company representatives, in order to engage all types of members/mentors.

It will also require project teams to prepare GitHub issues beforehand that can be picked up on the day for all types of levels.

# Tasks

_Whoever picks this up, feel free to create separate tickets and reference this one for each of below if needed_

- [ ] Identify internal projects we want to participate/collaborate in the day (#19)
- [ ] Identify/contact meetup groups we want to extend invite to. 
- [ ] Identify venue/company working in Python/Django to host / sponsor / participate with mentors
- [ ] Recruit mentors in Django community
- [ ] Prepare Meetup event and broadcast
