### ISSUE TITLE
Identify projects for Django Event day

### ISSUE THREAD

**Issue by khandelwalrinki** [womenhackfornonprofits/whfnp-wiki#19]
Relates to #18 (Host Django-focussed event) 

# What

In preparation for a Django-focussed hack day (#18), identify suitable active projects in the [WHFNP GitHub account](https://github.com/womenhackfornonprofits) that can participate in the day, and communicate with project leads in order to organise their GitHub repos so that there are tickets volunteers can easily pick up on the day, and that mentors can easily assist them with.

This will also help us experiment with streamlining some of our GitHub flows (e.g. labels, README formats, pull request process, etc) across projects, thus working towards a better method of linking new and existing volunteers to pieces of work they can pick up without too much overhead.

# Tasks

_Whoever picks this up, feel free to create separate tickets and reference this one for each of below if needed_

- [x] Make a list of WHFNP projects that are Django-based and active enough to participate in the day: [Ticket 21](https://github.com/womenhackfornonprofits/whfnp-wiki/issues/21)
- [ ] Contact PMs / project leads and help them identify + create isolated GitHub tickets that both team members and other volunteers can pick up on the day, labelled by skill level required, type of work + any other handy labels. These issues could be UX-based, code-based, or things that need review as some examples.
1. - [ ]  Contact [Pimp My Cause](https://github.com/womenhackfornonprofits/pimp-my-cause-django)
1. - [ ] Contact [OCD Action](https://github.com/womenhackfornonprofits/ocdaction)
1. - [ ] Contact [We Meet](https://github.com/womenhackfornonprofits/we-meet-django). Done: https://github.com/womenhackfornonprofits/we-meet-django/projects
1. - [ ]  Contact [Erehwon](https://github.com/marizoldi/Erehwon/tree/master/erehwon/)

- [ ] As part of these findings, create a wiki page in our [WHFNP wiki](https://github.com/womenhackfornonprofits/whfnp-wiki/wiki) that documents this way of organising GitHub tickets and links to example repos for reference. Can also include collaboration process HOWTO, e.g. open a pull request, code review etc
